drop table if exists user;
create table user
(
    id       bigint generated by default as identity,
    name     varchar(20),
    sex      varchar(50),
    age      int(3),
    birth_day  date,
    primary key (id)
);